---
- name: Rodar Superset Init Container
  docker_container:
    env_file: /home/{{ user }}/superset/env/{{ ambiente }}.env
    name: superset_init
    image: "{{ image }}:{{ version }}"
    command: ["/app/docker/docker-init.sh"]
    restart: yes
    recreate: yes
    state: started
    restart_policy: always
    user: "root"
    volumes:
    - /home/{{ user }}/superset/docker:/app/docker
    - /home/{{ user }}/superset/superset_home:/app/superset_home
